### ISSUE TITLE
can't find meta.pkl

### ISSUE THREAD

**Issue by hhxphh** [TaoHuUMD/SurMo#4]
Does the dataset include the meta.pkl file? I downloaded ZJU-MoCap and downloaded version 1.1.0 for Python 2.7 (female/male/neutral, 300 shape PCs) from the SMPL website, but I can't find meta.pkl. Or is meta.pkl the result of a file renaming?

**Comment by TaoHuUMD** [comment]
Hi, thanks for your interest. 

meta.pkl is a pre-processed file to facilitate training. The code will be updated this week.

The rendering results are saved [OneDrive](https://1drv.ms/f/c/cd958c29ffd57ddb/Ett91f8pjJUggM1-DQAAAAAB892JXlTtzxmciQIh0MC3bg?e=r1HjCH) for qualitative and quantitative comparisons.

**Comment by hhxphh** [comment]
thanks bro, wish you all the best in your research

**Comment by hhxphh** [comment]
By the way, will you provide a download method for meta.pkl? Or is it that the meta.pkl file is no longer needed after the code has been updated?

**Comment by TaoHuUMD** [comment]
It is no longer needed.

**Comment by hhxphh** [comment]
Got it， Thank you for Your Response.
while (universe.age < your_wonderful_code_arrival.time) {
         anticipation++;
}

**Comment by hhxphh** [comment]
Looking forward to your perfect code.

**Comment by TaoHuUMD** [comment]
Hi, these issues should have been resolved.

**Comment by hhxphh** [comment]
nice bro！thank u so much! I will try it.

**Comment by hhxphh** [comment]
Traceback (most recent call last):
  File "/home/hhx/code/SurMo/train_dist.py", line 269, in <module>
    model.module.compute_visuals(epoch)
  File "/home/hhx/code/SurMo/uvm_lib/models/model_motion.py", line 858, in compute_visuals
    if s in self.visual_names or s in self.test_visual_names:
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'test_visual_names'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 451444) of binary: /home/hhx/anaconda3/envs/surmo/bin/python
Traceback (most recent call last):
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_dist.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-15_21:41:02
  host      : phh
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 451444)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
it seems that self.test_visual_names isn't initialized by run 'bash scripts/zju/313_train.sh 0', i change the code in model_motion.py 166
        if self.opt.is_inference:
            self.test_visual_names = self.visual_names
            self.visual_names = ['visOutput']
To:

        if True:
            self.test_visual_names = self.visual_names
            self.visual_names = ['visOutput']
and it works now

**Comment by hhxphh** [comment]
Traceback (most recent call last):
File "/home/hhx/code/SurMo/train_dist.py", line 269, in
model.module.compute_visuals(epoch)
File "/home/hhx/code/SurMo/uvm_lib/models/model_motion.py", line 858, in compute_visuals
if s in self.visual_names or s in self.test_visual_names:
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in getattr
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'test_visual_names'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 451444) of binary: /home/hhx/anaconda3/envs/surmo/bin/python
Traceback (most recent call last):
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in
main()
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
launch(args)
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
run(args)
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
elastic_launch(
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
train_dist.py FAILED
Failures:
<NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
time : 2024-12-15_21:41:02
host : phh
rank : 0 (local_rank: 0)
exitcode : 1 (pid: 451444)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
it seems that self.test_visual_names isn't initialized by run 'bash scripts/zju/313_train.sh 0', i change the code in model_motion.py 166
if self.opt.is_inference:
self.test_visual_names = self.visual_names
self.visual_names = ['visOutput']
To:

    if True:
        self.test_visual_names = self.visual_names
        self.visual_names = ['visOutput']
and it works now

**Comment by hhxphh** [comment]
**When EVAL is performed after running every 5 epochs, an error message is reported:**

evaluate
Traceback (most recent call last):
  File "/home/hhx/code/SurMo/train_dist.py", line 304, in <module>
    for e_i, e_data in enumerate(eva_dataset, start=0):
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hhx/code/SurMo/uvm_lib/data/dataset_zju.py", line 427, in __getitem__
    ret = self.get_item_packed(index)
  File "/home/hhx/code/SurMo/uvm_lib/data/dataset_zju.py", line 396, in get_item_packed
    "posed_uv": self.tmprendering["posed_uv"][idx_cam], 
  File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError

**It could be an issue with the training dataset and the eval dataset**    
train_data_loader  = CreateDataLoaderDistributed(opt, train_dataset, train_sampler, "train")
    dataset = train_data_loader.load_data()
    dataset_size = len(train_data_loader)

    setup_training(opt, dataset_size)

    eva_data_loader = CreateDataLoader(opt, "evaluate")

**Comment by TaoHuUMD** [comment]
Glad that now you can run the training code. First, you may verify whether the test code works in your local environment.

**Comment by hhxphh** [comment]
I can test.py and get the rendered image just fine, but I think I know what the problem is:
In the dataset_zju.py:
```
if data_flag == "evaluate":
    
    known_id = data_dict["train_begin"][0]
    novel_id = int(data_dict["test_begin"][0] + data_dict["test_end"][0])
    novel_id = int(novel_id/2)

    self.eva_id = np.array([known_id, novel_id]).astype(int)
    
    self.ims = np.array([
        np.array(ims_data['ims'])[view_id[0]]
        for ims_data in np.array(annots['ims'])[self.eva_id]
    ]).ravel()
    self.cam_inds = np.array([
        np.arange(len(ims_data['ims']))[view_id[0]]
        for ims_data in np.array(annots['ims'])[self.eva_id]
    ]).ravel()
    
    self.num_cams = len(view_id)
    self.is_train = True
    return 
```
This results in "evaluate" mode not being defined:
```
if self.opt.load_tmp_rendering:
    dataset_name = self.opt.config[0].split("/")[1].split("_")[1]
    outdir = os.path.join("/media/hhx/Lenovo/data/SurMo/data/preprocessed_data/%s/CoreView_%s" % (self.opt.phase, dataset_name))
    self.tmprendering = np.load(os.path.join(outdir, "%s_tmp_rendering.npz" % self.opt.phase), allow_pickle=True)["arr_0"].item()#.item()

```
As a result, the following error message occurs:
```
File "/home/hhx/code/SurMo/uvm_lib/data/dataset_zju.py", line 427, in getitem
ret = self.get_item_packed(index)
File "/home/hhx/code/SurMo/uvm_lib/data/dataset_zju.py", line 396, in get_item_packed
"posed_uv": self.tmprendering["posed_uv"][idx_cam],
File "/home/hhx/anaconda3/envs/surmo/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 83, in getattr
raise AttributeError
AttributeError
```

**Comment by TaoHuUMD** [comment]
For evaluation during training, you can also load the train_tmp_rendering.npz to fix this problem. I will update this part later.

**Comment by hhxphh** [comment]
Thanks bro, I'll give it a try, and it's just a minor issue.
